In [1]:
import xarray as xr
import numpy as np
import glob

In [2]:
phase='calval_phase' # or science_phase
simu='eNATL60-BLB002' # or eNATL60-BLBT02
data='karin' # or nadir

In [11]:
#parameters for the region to consider
reg='MEDWEST'
latmin=35.1
latmax=44.4
lonmin=-5.7
lonmax=9.6


In [5]:
tdir='/work/ALT/swot/aval/wisa/tmp/inland_cleaning/swot_simulator_'+phase+'/'+simu+'-SSH-1h/'+data+'/'

In [43]:
file='/work/ALT/swot/aval/wisa/tmp/inland_cleaning/swot_simulator_calval_phase/eNATL60-BLB002-SSH-1h/karin//2009/SWOT_L2_LR_SSH_Basic_065_007_20090901T200611_20090901T205716_DG10_01.nc'

In [44]:
ds=xr.open_dataset(file)
latfile=ds.latitude
lonfile=ds.longitude
ssh=ds.ssh_karin    

In [45]:
ind_region=np.where((latfile < latmax) & (latfile > latmin) & 
        (lonfile < lonmax) & (lonfile > lonmin))

In [46]:
len(ind_region[0])

37701

In [47]:
numlines_region=ind_region[0]
numlines_region_unique=np.unique(numlines_region)

In [48]:
len(numlines_region_unique)

548

In [51]:
for k in np.arange(len(numlines_region_unique)):
    isdata=np.where(np.where(ssh[numlines_region_unique[k],:])==False)
    if len(isdata[0])>0:
        print('yeah')
    

In [49]:
print(lonfile[numlines_region_unique[0],:])

<xarray.DataArray 'longitude' (num_pixels: 71)>
array([3.735798, 3.714384, 3.692968, 3.67155 , 3.650129, 3.628707, 3.607283,
       3.585857, 3.564429, 3.542998, 3.521566, 3.500132, 3.478696, 3.457258,
       3.435818, 3.414376, 3.392932, 3.371486, 3.350038, 3.328588, 3.307136,
       3.285682, 3.264227, 3.242769, 3.221309, 3.199848, 3.178384, 3.156918,
       3.135451, 3.113981, 3.09251 , 3.071037, 3.049561, 3.028084, 3.006605,
       2.985124, 2.963641, 2.942156, 2.920669, 2.89918 , 2.877689, 2.856197,
       2.834702, 2.813205, 2.791707, 2.770206, 2.748704, 2.7272  , 2.705693,
       2.684185, 2.662675, 2.641163, 2.619649, 2.598134, 2.576616, 2.555096,
       2.533575, 2.512051, 2.490526, 2.468999, 2.44747 , 2.425939, 2.404406,
       2.382871, 2.361334, 2.339796, 2.318255, 2.296713, 2.275168, 2.253622,
       2.232074])
Coordinates:
    latitude   (num_pixels) float64 34.84 34.85 34.85 34.85 ... 35.1 35.1 35.1
    longitude  (num_pixels) float64 3.736 3.714 3.693 ... 2.275 2.254 2.

In [17]:
ind_track=np.where(np.isnan(ssh)==False)
if len(ind_track[0])>0:
    numlines_nonan=ind_track[0]
    numlines_nonan_unique=np.unique(numlines_nonan)
    for k in np.arange(len(numlines_nonan)):
        if (latfile[numlines_nonan[k],0] < latmax) & (latfile[numlines_nonan[k],0] > latmin) & 
        (lonfile[numlines_nonan[k],0] < lonmax) & (lonfile[numlines_nonan[k],0] > lonmin):
            ds_one=ds.isel(num_lines=numlines_nonan[k])
        if (latfile[numlines_nonan[k],-1] < latmax) & (latfile[numlines_nonan[k],-1] > latmin) & 
        (lonfile[numlines_nonan[k],-1] < lonmax) & (lonfile[numlines_nonan[k],-1] > lonmin):
            ds_one=ds.isel(num_lines=numlines_nonan[k])
        
                
        

In [37]:
ind_track=np.where(np.isnan(ssh)==False)
if len(ind_track[0])>0:
    numlines_nonan=ind_track[0]
    numlines_nonan_unique=np.unique(numlines_nonan)
    for k in np.arange(len(numlines_nonan_unique)):
        if (latfile[numlines_nonan_unique[k],0] < latmax) & (latfile[numlines_nonan_unique[k],0] > latmin) & (lonfile[numlines_nonan_unique[k],0] < lonmax) & (lonfile[numlines_nonan_unique[k],0] > lonmin):
            print('yeah')
        if (latfile[numlines_nonan_unique[k],-1] < latmax) & (latfile[numlines_nonan_unique[k],-1] > latmin) & (lonfile[numlines_nonan_unique[k],-1] < lonmax) & (lonfile[numlines_nonan_unique[k],-1] > lonmin):
            print('yeah')


KeyboardInterrupt: 

In [38]:
len(numlines_nonan_unique)

653

In [27]:
numlines_nonan=ind_track[0]

In [32]:
numlines_nonan

array([6686, 6686, 6686, ..., 7575, 7575, 7576])

In [28]:
numlines_nonan_unique=np.unique(numlines_nonan)

In [33]:
numlines_nonan_unique

array([6686, 6687, 6688, 6689, 6690, 6691, 6692, 6693, 6694, 6695, 6696,
       6697, 6698, 6699, 6700, 6701, 6702, 6703, 6704, 6705, 6706, 6707,
       6708, 6709, 6710, 6711, 6712, 6713, 6714, 6715, 6716, 6717, 6718,
       6719, 6720, 6721, 6722, 6723, 6724, 6725, 6726, 6727, 6728, 6729,
       6730, 6731, 6732, 6733, 6734, 6735, 6736, 6737, 6738, 6739, 6740,
       6741, 6742, 6743, 6744, 6745, 6746, 6747, 6748, 6749, 6750, 6751,
       6752, 6753, 6754, 6755, 6756, 6757, 6758, 6759, 6760, 6761, 6762,
       6763, 6764, 6765, 6766, 6767, 6768, 6769, 6770, 6771, 6772, 6773,
       6774, 6775, 6776, 6777, 6778, 6779, 6780, 6781, 6782, 6783, 6784,
       6785, 6786, 6787, 6788, 6789, 6790, 6791, 6792, 6793, 6794, 6795,
       6796, 6797, 6798, 6799, 6800, 6801, 6802, 6803, 6804, 6805, 6806,
       6807, 6808, 6809, 6810, 6811, 6812, 6813, 6814, 6815, 6816, 6817,
       6818, 6819, 6820, 6821, 6822, 6823, 6824, 6825, 6826, 6827, 6828,
       6829, 6830, 6831, 6832, 6833, 6834, 6835, 68

In [31]:
print(653*71)

46363


In [24]:
len(ind_track[1])

30861

In [21]:
ssh[ind_track[0][0],ind_track[1][0]]

<xarray.DataArray 'ssh_karin' ()>
array(-0.2701)
Coordinates:
    latitude   float64 ...
    longitude  float64 ...
Attributes:
    long_name:      sea surface height
    standard_name:  sea surface height above reference ellipsoid
    units:          m
    valid_min:      -15000000
    valid_max:      150000000
    comment:        Fully corrected sea surface height measured by KaRIn. The...
    post_process:   land masked used bilinear mask

In [14]:
ssh

<xarray.DataArray 'ssh_karin' (num_lines: 9868, num_pixels: 71)>
[700628 values with dtype=float64]
Coordinates:
    latitude   (num_lines, num_pixels) float64 ...
    longitude  (num_lines, num_pixels) float64 ...
Dimensions without coordinates: num_lines, num_pixels
Attributes:
    long_name:      sea surface height
    standard_name:  sea surface height above reference ellipsoid
    units:          m
    valid_min:      -15000000
    valid_max:      150000000
    comment:        Fully corrected sea surface height measured by KaRIn. The...
    post_process:   land masked used bilinear mask

In [12]:
ds

<xarray.Dataset>
Dimensions:                (num_lines: 9868, num_pixels: 71)
Coordinates:
    latitude               (num_lines, num_pixels) float64 ...
    longitude              (num_lines, num_pixels) float64 ...
Dimensions without coordinates: num_lines, num_pixels
Data variables:
    time                   (num_lines) datetime64[ns] ...
    ssh_karin              (num_lines, num_pixels) float64 ...
    ssh_karin_true         (num_lines, num_pixels) float64 ...
    err_karin              (num_lines, num_pixels) float64 ...
    err_phase              (num_lines, num_pixels) float64 ...
    err_timing             (num_lines, num_pixels) float64 ...
    err_roll               (num_lines, num_pixels) float64 ...
    err_wet_troposphere    (num_lines, num_pixels) float64 ...
    err_baseline_dilation  (num_lines, num_pixels) float64 ...
Attributes:
    Conventions:                        CF-1.7
    title:                              Level 2 Low Rate Sea Surface Height D...
    institution:                        CNES/JPL
    source:                             Simulate product
    history:                            2020-07-23 07:57:23 : Creation
    platform:                           SWOT
    references:                         Gaultier, L., C. Ubelmann, and L.-L. ...
    reference_document:                 D-56407_SWOT_Product_Description_L2_L...
    contact:                            CNES aviso@altimetry.fr, JPL podaac@p...
    cycle_number:                       1
    pass_number:                        5
    time_coverage_start:                2009-06-30T04:24:23.474930Z
    time_coverage_end:                  2009-06-30T05:15:29.068450Z
    time_coverage_duration:             P51M5S
    time_coverage_resolution:           P1S
    geospatial_lon_min:                 0.00031835228732314937
    geospatial_lon_max:                 359.99989117967135
    geospatial_lat_min:                 -78.2917079793339
    geospatial_lat_max:                 78.29203332764706
    left_first_longitude:               298.9883586467037
    left_first_latitude:                -78.2917079793339
    left_last_longitude:                106.11694307126041
    left_last_latitude:                 77.03298330608429
    right_first_longitude:              298.97971371631036
    right_first_latitude:               -77.03265914467408
    right_last_longitude:               106.11996076639889
    right_last_latitude:                78.29203332764706
    wavelength:                         0.008385803020979
    orbit_solution:                     POE
    xref_input_l1b_lr_intf_file:        N/A
    xref_input_static_karin_cal_file:   N/A
    xref_input_static_geophys_files:    N/A
    xref_input_dynamic_geophys_files:   N/A
    xref_input_l1_nalt_gdr_files:       N/A
    xref_input_int_lr_xover_cal_files:  N/A
    xref_input_l2_rad_gdr_files:        N/A
    ellipsoid_semi_major_axis:          1.0
    ellipsoid_flattening:               0.0

In [10]:
latfile

<xarray.DataArray 'latitude' (num_lines: 9868, num_pixels: 71)>
[700628 values with dtype=float64]
Coordinates:
    latitude   (num_lines, num_pixels) float64 ...
    longitude  (num_lines, num_pixels) float64 ...
Dimensions without coordinates: num_lines, num_pixels
Attributes:
    long_name:      latitude (positive N, negative S)
    standard_name:  latitude
    units:          degrees_north
    valid_min:      -80000000
    valid_max:      80000000
    comment:        Latitude of measurement [-80,80]. Positive latitude is No...

In [ ]:
def check_one_file_in_region(latmin,latmax,lonmin,lonmax,file):
    ds=xr.open_dataset(file)
    latfile=ds.latitude
    lonfile=ds.longitude
    